### ISSUE TITLE
Correción errores varios

### ISSUE THREAD

**Issue by jbrizio** [ModernizacionMuniCBA/agenda-cultural-de-cordoba#1]
Estimados,

He visto que han realizado una copia a semejanza del [repositorio de la feria del libro](https://github.com/ModernizacionMuniCBA/feria-del-libro) para llevar adelante el desarrollo de una aplicación mobile de similares caracteristicas para la agenda cultural de nuestra ciudad. Por lo que los errores que les mencionaré a continuación son los mismos en ambos repositorios:
- No se sigue un [lineamiento o standard](http://codeguide.co/) en el código HTML
  - Inconsistencia en la indentación
  - Espacios en blancos
- El código HTML no pasa la [validación de la W3C](https://validator.w3.org/)
- Código comentado
- Imagenes utilizadas sin comprimir (Optimizar para conexiones móviles)
- La fuente que están utilizando "glyphicons", [no está permitida para este tipo de proyectos](http://glyphicons.com/license/#licensetext)

**Comment by avdata99** [comment]
Muchas gracias @jbrizio. Vamos a tener en cuenta tus observaciones
